import React from 'react';
import Head from 'next/head';
import GlobalStyle from '@/styles/globals'
// components
import Header from '../components/Header';
import Banner from '../components/Banner';


export default function Home() {
  return (
    <>
      <Head>
        <title>Primavera Store</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <GlobalStyle />
      <main className="">
        <Header />
        <Banner />
      </main>
    </>
  )
}
