import React from 'react';
import Head from 'next/head';
import GlobalStyle from '@/styles/globals'
import Header from '../components/Header';
import IncludingProductForm from '../components/IncludingProductForm';


export default function Home() {
  return (
    <>
      <Head>
        <title>Controle</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <GlobalStyle />
      <main className="">
        <Header />
        <main>
          
            <IncludingProductForm />
        </main>
      </main>
    </>
  )
}